// Scraped from the r/FashionReps community Superbuy guide (one-time snapshot),
// trimmed to the ordering walkthrough: adding items to cart and selecting the
// shipping destination. Content by /u/hyperionfr - full credit to the author.

export const SUPERBUY_GUIDE = {
  title: "How to order via Superbuy",
  author: "u/hyperionfr on r/FashionReps (from GUIDE 4.0)",
  sourceUrl:
    "https://www.reddit.com/r/FashionReps/comments/aecrl5/guide_40_the_biggest_best_full_superbuy_agent/",
  text: "As always thanks to\nu/wailll\nfor his\npost\n\n- Find the item you want on Taobao. Use this subreddit, try to find it yourself with\nimage search\nor Google translate, whatever. For this example, we'll use the A$AP Rocky x Guess Tee from UnionKingdom.\n\n- Go to Superbuy, and hover over the Shopping Agent button on the navbar. Click the blue box and paste your Taobao link into it.\n\n- You will be taken to a page like\nthis\n. Here, Superbuy translates the color and size options for you, and all you need to do is select the color and size you want. After, you can either\nAdd to Cart\nor\nBuy Now\n. For this example, we'll assume that this shirt it the only thing you want.\n\n- You will next be taken to\nthis page\n. Here, you have to select your country from the\nChoose Destination Country\nbox, then hit submit to be taken to the payment screen.\n\n- If you have an existing balance in your Superbuy account from previous purchases that you have returned, you can use that to buy the product.\nI have 91.06 yuan in my account already, so I just need to pay 18.94 yuan for this 110 yuan tee.\n\n- Here\n, just select Paypal and pay for your order. Sometimes Superbuy will not allow you to use PayPal and that is when you need to simply top up your balance instead of doing a direct order with PayPal.\n\n- Now, just wait until the seller ships his order. Once it arrives in the Superbuy warehouse, you will receive a notification.\n\n- Once your product arrives,\nhover over your username in the navbar and select My Warehouse\n. Here, you can view\nQC, or quality control, pictures that Superbuy takes\n. One con of using Superbuy is their picture taking skills. To receive better pictures, you have to contact their\nlive chat\nand give them your order number and request better QC pictures.\n\n- If you're satisfied with your order, select it and click\nSubmit\nin the lower right corner.\nHere\n, you can choose your preferred shipping method. The fashionreps favorite currently is EMS, but it's up to you what line you would like to use. Just select the shipping line, then click\nSubmit Delivery Order\nto have Superbuy pack up your products and send it to your door.\n\n",
};
